version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_URL: mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      #MAIL_SERVER: mailhog
      #MAIL_PORT: 1025
      #MAIL_USE_TLS: "False"
      #MAIL_USE_SSL: "False"
      #MAIL_USERNAME: ""
      #MAIL_PASSWORD: ""
      #MAIL_DEFAULT_SENDER: ${MAIL_DEFAULT_SENDER}
      MAIL_SERVER: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USE_TLS: "True"
      MAIL_USE_SSL: "False"
      MAIL_USERNAME: "desarolloappudc@gmail.com"
      MAIL_PASSWORD: "fdtl hacv ohhn bqja"
      MAIL_DEFAULT_SENDER: desarolloappudc@gmail.com
    depends_on:
      - db
      #- mailhog
    volumes:
      - .:/app
    restart: on-failure

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  #mailhog:
   # image: mailhog/mailhog:latest
   # ports:
   #   - "8025:8025"
   #   - "1025:1025"
   # restart: on-failure

volumes:
  db_data:
